#!/bin/bash
#
# Time of day greeting (Author: Erik Nystrom, Date: 11/17/2015)
#
# usage: ./greet [hour between 0-23]
#
if [[ $# -eq 0 ]] 
   then 
      hour=`date +%H`      # command output substitution
   else 
      hour=$1
fi
#
if [[ $hour -lt 12 ]] 
   then
      echo "Good Morning!"
   else
      if [[ $hour -lt 18 ]] 
         then 
            echo "Good Afternoon!"
         else 
            echo "Good Evening!"
      fi
fi
#
exit 0
#

