#!/bin/bash
# The program will remove the named file/directory from
# the current working directory and place it in ~/.trash.
# Invoke as
#
#     ./delete filename
#
# Check for argument
if [[ $# -ne 1 ]] 
   then
      echo "usage: $0 filename"
      exit 1
fi
# Check if the named entry exists in the cwd
if [[ !(-e $1) ]] 
   then
      echo "$0: $1 does not exist"
      exit 2
fi
# Check if ~/.trash exists; create one if necessary
if [[ !(-d ~/.trash) ]] 
   then
      mkdir ~/.trash
fi
# Check if ~/.trash contains an entry with the given name
if [[ -e ~/.trash/$1 ]] 
   then
      echo -n "$0: $1 exists in .trash. Overwrite? (y/n) "
      read resp
      if [[ $resp == "y" ]] 
         then
           rm -rf ~/.trash/$1
         else
            echo "$0: $1 was not deleted"
            exit 3
      fi
fi
# Move the entry from the cwd to ~/.trash
mv $1 ~/.trash
exit 0
#
